### ISSUE TITLE
Cannot read property _name of undefined

### ISSUE THREAD

**Issue by Equals182** [Wikunia/brackets-jQuinter#4]
I got this error on Brackets' start (I guess - my ext wasn't loaded yet)

```
Unhandled exception in getAllFiles handler: TypeError: Cannot read property '_name' of undefined TypeError: Cannot read property '_name' of undefined
    at JQueryHinter.getHintsForSingleFile (file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/jquinter/hints.js:200:31)
    at getHintsForFilesRec (file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/jquinter/hints.js:168:24)
    at JQueryHinter.getHintsForFiles (file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/jquinter/hints.js:157:13)
    at Object.<anonymous> (file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/jquinter/hints.js:107:24)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith [as resolveWith] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at Object.e.(anonymous function) [as resolve] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:28704)
    at Object.<anonymous> (file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/jquinter/hints.js:136:28)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith [as resolveWith] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27724)
```

That's what I have before and after this error:

```
 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at _handlerOn (file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/enturn.quick-search/main.js:195:9)
    at file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/enturn.quick-search/main.js:223:21
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at _notifyActiveEditorChanged (/editor/EditorManager.js:165:17)
    at _handleCurrentFileChange (/editor/EditorManager.js:182:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at eval (/view/MainViewManager.js:1107:29)
/project/ProjectModel.js:500
Unhandled exception in getAllFiles handler: TypeError: Cannot read property '_name' of undefined TypeError: Cannot read property '_name' of undefined
    at JQueryHinter.getHintsForSingleFile (file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/jquinter/hints.js:200:31)
    at getHintsForFilesRec (file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/jquinter/hints.js:168:24)
    at JQueryHinter.getHintsForFiles (file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/jquinter/hints.js:157:13)
    at Object.<anonymous> (file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/jquinter/hints.js:107:24)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith [as resolveWith] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at Object.e.(anonymous function) [as resolve] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:28704)
    at Object.<anonymous> (file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/jquinter/hints.js:136:28)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith [as resolveWith] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27724)
NodeDebugUtils.js:117 [node-log 2:36:21 PM] [eqFTP-ftpDomain] Loaded
main.js:1633 [eqFTP] Loaded (v0.7.0)
```

version 0.3.0

**Comment by Wikunia** [comment]
Hi Alex,

does it happen at the beginning or after trying to use this extension?

**Comment by Wikunia** [comment]
File is a Brackets object which should always has the key `_name` :/

**Comment by Wikunia** [comment]
Maybe your project was empty? Then this should fix it ;) (Install from url)

**Comment by Equals182** [comment]
It happened right at the beginning, I assume after Brackets processed file that was opened earlier, before closing Brackets.

**Comment by Equals182** [comment]
That was a one-time issue. I've restarted Brackets and everything worked fine. Maybe it was a minor Brackets' bug.

**Comment by Wikunia** [comment]
Alright! Reopen if it happens again ;)

**Comment by Equals182** [comment]
Will do :+1:
